obj-$(CONFIG_INV_ICM42607X) += inv-icm42607x.o
inv-icm42607x-y += inv_icm42607x_core.o
inv-icm42607x-y += inv_icm42607x_gyro.o
inv-icm42607x-y += inv_icm42607x_accel.o
inv-icm42607x-y += inv_icm42607x_buffer.o
inv-icm42607x-y += inv_icm42607x_temp.o
inv-icm42607x-y += inv_icm42607x_timestamp.o

obj-$(CONFIG_INV_ICM42607X_SPI) += inv-icm42607x-spi.o
inv-icm42607x-spi-y += inv_icm42607x_spi.o
