obj-$(CONFIG_INV_ICM42607P) += inv-icm42607p.o
inv-icm42607p-y += inv_icm42607p_core.o
inv-icm42607p-y += inv_icm42607p_gyro.o
inv-icm42607p-y += inv_icm42607p_accel.o
inv-icm42607p-y += inv_icm42607p_buffer.o
inv-icm42607p-y += inv_icm42607p_temp.o
inv-icm42607p-y += inv_icm42607p_timestamp.o

obj-$(CONFIG_INV_ICM42607P_SPI) += inv-icm42607p-spi.o
inv-icm42607p-spi-y += inv_icm42607p_spi.o
